### ISSUE TITLE
Incomplete and Wrong: Concourse GitHub Auth Install Instructions

### ISSUE THREAD

**Issue by Jeeppler** [concourse/docs#111]
I took quite a while to figure out that this section from the [`GitHub Auth`](https://concourse-ci.org/install.html#github-auth-config) does not work:

"First you need to create an OAuth application on GitHub.

The callback URL will be the external URL of your Concourse server with /sky/issuer/callback appended. For example, Concourse's own CI server's callback URL would be https://ci.concourse-ci.org/sky/issuer/callback."

I do not know when `/sky/issuer/callback` was correct. However, for me it did not work at all. What actually has to be appended is `/auth/github/callback`. In addition, it would be nice to mentioned that `https://ci.concourse-ci.org/auth/github/callback` has to be inserted into the `Authorization callback URL` field in GitHub. An example screenshot can be found here: https://github.com/concourse/concourse/issues/780#issuecomment-270226766

Without the `/auth/github/callback/` I received the [`Redirect URI mismatch`](https://developer.github.com/apps/managing-oauth-apps/troubleshooting-oauth-app-access-token-request-errors/#redirect-uri-mismatch) error from GitHub.

Furthermore, the `Configuring the client section` is incomplete, because you also have to specify the `--external-url <hostname>` parameter or if you use the Helm chart set `concourse.externalURL: "<hostname>"` in your `values.yaml` to your hostname. The hostname has to be in the form `http(s)://<your-domain>.<tld>:<port>/`. For example: `https://ci.concourse-ci.org:8080/`.

**Comment by jpluscplusm** [comment]
As a datapoint, we upgraded 3.x to 4.2.1 and GH auth continued working *without* updating the GH callback URL. I.e. with the 3.x `/auth/github/callback` setting. /cc @LeePorte

**Comment by LeePorte** [comment]
`/auth/github/callback` is currently in use.

**Comment by au-tools-test** [comment]
Is `/auth/github/callback` still the right answer ATM?

**Comment by au-hao** [comment]
Is `auth/github/callback` still the right answer ATM?

**Comment by vito** [comment]
The auth docs were rewritten and restructured a while back and as far as I can tell are correct. The URL to set is `/sky/issuer/callback`. I'm not sure what version of Concourse you were using, @Jeeppler, but it sounds like it was older than 4.x where it changed to `/sky/issuer/callback` with `/auth/github/callback` still supported for backwards-compatibility.
