### ISSUE TITLE
Concourse from quick start does not work as expected

### ISSUE THREAD

**Issue by IgnusG** [concourse/docs#114]
Following the [quick start tutorial](https://www.concourse-ci.org/getting-started.html) I'm getting the following errors after pulling the images is completed:

```
concourse-db_1  | 2018-09-23 20:20:01.602 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
concourse-db_1  | 2018-09-23 20:20:01.602 UTC [1] LOG:  listening on IPv6 address "::", port 5432
concourse-db_1  | 2018-09-23 20:20:01.669 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
concourse-db_1  | 2018-09-23 20:20:01.793 UTC [62] LOG:  database system was shut down at 2018-09-23 20:20:01 UTC
concourse-db_1  | 2018-09-23 20:20:01.832 UTC [1] LOG:  database system is ready to accept connections
concourse_1     | {"timestamp":"1537734003.144883156","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1537734009.174848795","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
```

I had it running around 2 months ago I think. I'm confused why concourse is trying to connect on 172.20.0.2.
I tried removing the images and pulling the again with no luck.

**Comment by jama-pivotal** [comment]
Weird, I just tried and it works for me. Going to leave this open in case someone else has ideas on how to help

**Comment by BlueTac92** [comment]
I'm seeing the same issue. I can telnet from my local to the postgres container on port 5432 but not to the concourse container. I've tried clearing all images and containers but the issue continues.

It seems like it's an issue with the networking.

```
Starting concourse_concourse-db_1 ... done
Starting concourse_concourse_1    ... done
Attaching to concourse_concourse-db_1, concourse_concourse_1
concourse-db_1  | 2019-04-14 02:51:00.838 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
concourse-db_1  | 2019-04-14 02:51:00.838 UTC [1] LOG:  listening on IPv6 address "::", port 5432
concourse-db_1  | 2019-04-14 02:51:00.910 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
concourse-db_1  | 2019-04-14 02:51:01.028 UTC [23] LOG:  database system was shut down at 2019-04-14 02:50:19 UTC
concourse-db_1  | 2019-04-14 02:51:01.040 UTC [1] LOG:  database system is ready to accept connections
concourse_1     | {"timestamp":"1555210263.955424070","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1555210269.982234001","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1555210276.008932352","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1555210282.035616875","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1555210288.065488815","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse_1     | {"timestamp":"1555210294.088818550","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
concourse-db_1  | 2019-04-14 02:51:39.296 UTC [30] LOG:  invalid length of startup packet
concourse_1     | {"timestamp":"1555210300.118893862","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}
```

**Comment by BlueTac92** [comment]
```Starting concourse_concourse-db_1 ... doneStarting concourse_concourse_1    ... doneAttaching to concourse_concourse-db_1, concourse_concourse_1concourse-db_1  | 2019-04-14 02:51:00.838 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432concourse-db_1  | 2019-04-14 02:51:00.838 UTC [1] LOG:  listening on IPv6 address "::", port 5432concourse-db_1  | 2019-04-14 02:51:00.910 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"concourse-db_1  | 2019-04-14 02:51:01.028 UTC [23] LOG:  database system was shut down at 2019-04-14 02:50:19 UTCconcourse-db_1  | 2019-04-14 02:51:01.040 UTC [1] LOG:  database system is ready to accept connectionsconcourse_1     | {"timestamp":"1555210263.955424070","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse_1     | {"timestamp":"1555210269.982234001","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse_1     | {"timestamp":"1555210276.008932352","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse_1     | {"timestamp":"1555210282.035616875","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse_1     | {"timestamp":"1555210288.065488815","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse_1     | {"timestamp":"1555210294.088818550","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}concourse-db_1  | 2019-04-14 02:51:39.296 UTC [30] LOG:  invalid length of startup packetconcourse_1     | {"timestamp":"1555210300.118893862","source":"atc","message":"atc.db.failed-to-open-db-retrying","log_level":2,"data":{"error":"dial tcp 172.20.0.2:5432: connect: no route to host","session":"3"}}```

**Comment by deniseyu** [comment]
Closing this out since we're transitioning away from the quick start instructions, and our officially supported "kick the tires" workflow is docker-compose.
