### ISSUE TITLE
"Aside" blockquote and content looked haphazard and made me confused 

### ISSUE THREAD

**Issue by sampeinado** [concourse/docs#117]
**The Problem**
The "aside" on this page that describes how to target powershell for intercepting a job on a Windows worker was confusing to me because it is sorting floating off on its own. I wasn't sure how I should understand this information in relation to the main body. 

Questions that arose in my mind were, is this section just misplaced? Should it be in the main body or is it intentionally separate? What part of the body is it intended to comment on? 

**A Modest Proposal**
Perhaps the `aside` class can be a bit wider, or have a bit more separation from the body? Or maybe give it a light background color? 

Its showing up like this in chrome:

![screen shot 2018-10-01 at 5 41 25 pm](https://user-images.githubusercontent.com/35495560/46317540-4f8f5480-c5a1-11e8-8ab3-24851ffb7f04.png)

Maybe it could be like this? 

![screen shot 2018-10-01 at 5 49 57 pm](https://user-images.githubusercontent.com/35495560/46317850-77cb8300-c5a2-11e8-826d-7f8308376b28.png)

Open to suggestions.

**Comment by vito** [comment]
this is fixed now; asides are just indented inline instead
