### ISSUE TITLE
Vague chaining jobs example

### ISSUE THREAD

**Issue by jpds** [concourse/docs#120]
The "Chaining jobs" example here:

https://github.com/concourse/docs/blob/51ff49fffc9caebc13508d03b478deece164830c/lit/reference/pipelines.lit#L94-L119

...is slightly vague in that it references a `unit` 4 different times. It isn't immediately clear what the `unit` in the `build` `passed:` stage refers to - it ultimately refers to the job name but it would be easier if these had different names for clarity.

**Comment by vito** [comment]
makes sense, i'll update it!
