### ISSUE TITLE
Search functionality considers each letter as a token instead of the word

### ISSUE THREAD

**Issue by h4xnoodle** [concourse/docs#125]
I'm trying to search for information about spaces on the website.

It seems that each character is considered a token for the search criteria, instead of the whole word. I would expect to find zero results if there are no mentions of 'space' or a page that talks about spaces.

![screen shot 2018-11-06 at 11 03 25 am](https://user-images.githubusercontent.com/105841/48076696-bd87f680-e1b3-11e8-9dfa-de873ec0a116.png)

**Comment by vito** [comment]
It's a fuzzy search so false positives are sometimes possible, but I've made it a bit stricter now so there are fewer junk results.

**Comment by vito** [comment]
Meh, now it's not turning up results that include your substring but don't start with it. I'll keep tweaking.
