### ISSUE TITLE
Components run into each other on reasonable desktop browser size on download page

### ISSUE THREAD

**Issue by h4xnoodle** [concourse/docs#170]
At half-width on the large Mac, (1195px width browser) the release notes page has components that run into each other. Decreasing the browser a bit more snaps into the next responsive threshold.

![screen shot 2019-03-07 at 10 33 12 am](https://user-images.githubusercontent.com/105841/53968413-fafa8300-40c4-11e9-9a20-3d836f4ff1fd.png)

**Comment by vito** [comment]
:+1: thanks for the report, looks like i just need an earlier breakpoint

**Comment by vito** [comment]
did a bit more work to also make it look nicer when it *does* wrap
