### ISSUE TITLE
Document registration of team-specific workers

### ISSUE THREAD

**Issue by cirocosta** [concourse/docs#176]
Hey,

I couldn't find a good reference in our docs to give around the possibility and consequences of using team-specific workers.

It seems to me that it'd be useful to note:
- how it affects scheduling (e.g. https://github.com/concourse/concourse/issues/1865#issuecomment-464166994), and
-  the behavior of check containers in the presence of such specialized containers (there's a bit around complications here https://concourse-ci.org/global-resources.html#complications-with-reusing-containers , but it'd be nice to see that clearly when wondering about providing a team worker or not).

Wdyt?

Thanks

**Comment by YoussB** [comment]
@cirocosta Added more comments to the PR

**Comment by au-hao** [comment]
We are looking for how to assign specific worker to specific team.  Do you know where can we get any example, just for a quick reference, which can be put here before you releasing a doc.

**Comment by rikkuness** [comment]
@au-hao I just spent hours trying to work this out, but starting the worker with `CONCOURSE_TEAM` set to a value that matches the team seems to assign the worker to a team, couldn't find it documented anywhere.

**Comment by taylorsilva** [comment]
This is now documented: https://concourse-ci.org/concourse-worker.html#team-workers
<img width="815" alt="image" src="https://user-images.githubusercontent.com/4583837/125527665-9add22d5-04cc-4fff-9523-2000bb53ca43.png">
