### ISSUE TITLE
fly pause-resource incorrect redirect

### ISSUE THREAD

**Issue by YoussB** [concourse/docs#192]
The link (from [here](https://concourse-ci.org/reference.html)): https://concourse-ci.org/managing-resources.html#fly-pause-resource
goes to `check-resource` instead of going to a page for `fly pause-resource`

**Comment by vito** [comment]
[this](https://concourse-ci.org/reference.html) looks like a stale/dead page - I wouldn't trust any links coming from it. it should probably just be removed.

**Comment by taylorsilva** [comment]
Fixed. Check https://github.com/concourse/docs/issues/194 for context.
