### ISSUE TITLE
Remove old pages from website

### ISSUE THREAD

**Issue by taylorsilva** [concourse/docs#194]
Not sure how this is happening, but it looks like some pages from the older version of the site didn't get removed.

Example I found in a community resource: https://concourse-ci.org/implementing-resources.html

Another example from slack: https://pivotal.slack.com/archives/C6TL2PMC7/p1554503971059900

We should remove these files because some people find these _zombie_ links in ReadMe's in community resources and get confused seeing these broken pages.

**Comment by vito** [comment]
This should be fixed the next time we push our docs: https://github.com/concourse/docs/blob/v5.2/ci/build#L22-L24
