### ISSUE TITLE
docs for `vars` property in task step confusing and repetitive

### ISSUE THREAD

**Issue by kdvolder** [concourse/docs#219]
Two points. 

1) A section of the 'vars' doc section seems to be repeated (some kind of copy-pasting error maybe?).

See: https://concourse-ci.org/task-step.html#task-step-vars

See the code snippet: 

```
plan:
- get: my-repo
- task: integration
  file: my-repo/ci/task.yml
  vars:
    text: "Hello World!"
```

It is repeated twice. Was the second snippet meant to be something else? Or was it just accidentally pasted twice?

2) I don't think I quite understand the difference between 'vars' and 'params'. There's some explanation in the docs but it still leaves me scratching my head a bit. The main difference is that 'vars' supports interpolation? Not sure what exactly that means in concrete terms (i.e. what exactly is it that we *can* do with 'vars' but not 'params'.

PS: About point 2), I'm sorry I know this is a bit of a vague complaint. If it seems too hard to improve this without making it incredibly verbose, I understand, but I thought I'd at least report it and give you guys a chance to take another look and decide. I figure you might as well, while you are already looking at it to take care of point 1)

**Comment by vito** [comment]
Thanks for the feedback. :) vars vs. params is definitely prone to confusion, I'll take a look
