### ISSUE TITLE
Let's Encrypt Docs aren't visible on the website

### ISSUE THREAD

**Issue by dfreilich** [concourse/docs#226]
While #218 addressed creating the Let's Encrypt docs, those docs aren't available on the website yet (https://concourse-ci.org/concourse-web.html), and you have to build the scripts locally to see them. Could you rebuild the website so that they are current? 

Thanks!

**Comment by vito** [comment]
it's there now: https://concourse-ci.org/concourse-web.html#lets-encrypt
