### ISSUE TITLE
Document `fly intercept`

### ISSUE THREAD

**Issue by pivotal-jamie-klassen** [concourse/docs#232]
Some folks will be mainly using the docs site as a reference for fly, since there are already several subcommands documented there. We should probably try to bring it completely up-to-date, but I just want to capture a single important subcommand for now.

**Comment by vito** [comment]
Isn't it already documented? https://concourse-ci.org/builds.html#fly-intercept

**Comment by pivotal-jamie-klassen** [comment]
Yeah, it totally is... I guess I expected to see it in the 'fly cli' section

**Comment by vito** [comment]
@pivotal-jamie-klassen this is open for feedback, but I moved away from having one big 'fly cli' section in favor of integrating 'fly' throughout topical sections in the docs.
