### ISSUE TITLE
Hello world small improvement

### ISSUE THREAD

**Issue by alvaropinot** [concourse/docs#24]
IMHO it might be easier to follow (not that it is that hard :P) if a small description about login was added something like `login > selecting *main* team > clicking login as there is no password` prior to refreshing the page as stated at https://github.com/concourse/docs/blob/60c4c722e702dc026b1fc734462a4da6cdc5df82/lit/using-concourse/hello-world.lit#L55 specially because the UI, when logged out, shows the default message:

> no pipelines configured
> first, download the CLI tools:
> then, use `fly set-pipeline` to set up your new pipeline

which could lead into thinking that the previous set pipeline `fly -t lite set-pipeline -p hello-world -c hello.yml` command had failed.

**Comment by alvaropinot** [comment]
After reading starkandwayne/concourse-tutorial something like their copy might work :)


> Login to Concourse Web UI
> 
> Visit the pipeline URL http://192.168.100.4:8080/teams/main/pipelines/helloworld
> 
> It is a private pipeline and currently you are not logged in to the Concourse Web UI. You will be redirected to a login page.
> 
> dashboard-login
> 
> Click "Login" and you'll be redirected back to your pipeline.
> 
> Why did you not have to enter any username/password? Excellent question, indeed. It's because your current fly -t tutorial deployment of Concourse has had authentication disabled. In a future lesson we will upgrade to a more robust installation of Concourse with passwords and fanciness.
> 
>

**Comment by vito** [comment]
We actually just delegate to the Tutorial for this kind of material now, so I'll call this "done". :)
