### ISSUE TITLE
Document minimum number of connections that Postgres must allow

### ISSUE THREAD

**Issue by cirocosta** [concourse/docs#244]
Hey,

Despite the fact that one can observe that a certain number of connections are kept by the pools that we create, and that over time ATC goes over that stable amount, we don't document anywhere what's the maximum that it can reach (32 per backend).

Although the default BOSH postgres release gives us some [good number of max connections by default (500)](https://github.com/cloudfoundry/postgres-release/blob/602e0edb668c91a4bfa1cb4a4462bcce27eb055c/jobs/postgres/spec#L62-L64), that's not necessarily true to other distributions (including CloudSQL, which has a variable number of max conns depending on instance type: https://cloud.google.com/sql/docs/postgres/flags#postgres-m).

I can see that this could be a matter of providing a simple calculation that one could perform: #web_replicas * 64 (or whatever ends up being true after https://github.com/concourse/concourse/issues/4025) in the [Running a PostgreSQL section](https://concourse-ci.org/postgresql-node.html).

Wdyt?

thanks!

**Comment by cirocosta** [comment]
(might be worth documenting that those values are configurable: https://github.com/concourse/concourse/blob/c5dc52503a651c3858f756b22946d612b5bfa367/atc/atccmd/command.go#L102)

**Comment by pivotal-jamie-klassen** [comment]
@cirocosta is this fixed by #315?

**Comment by cirocosta** [comment]
yepp!
