### ISSUE TITLE
Review docs

### ISSUE THREAD

**Issue by jomsie** [concourse/docs#251]
https://github.com/concourse/concourse/issues/4408

This is an issue for me to go over the docs on (hopefully) friday and fix/purge broken/old documentation.

This will both hopefully improve the docs and improve my own understanding!

**Comment by jomsie** [comment]
I didn't have time on Friday to do this, but I guess it'll be an ongoing thing... I'll keep progress updated in this issue.

**Comment by jomsie** [comment]
https://concourse-ci.org/volume-internals.html - missing types of resources

**Comment by taylorsilva** [comment]
The last handful of PR's I've made have addressed this.
