### ISSUE TITLE
Explain the difference between `on_failure`, `on_error`, `on_abort`

### ISSUE THREAD

**Issue by kdvolder** [concourse/docs#267]
The docs I'd like to see elaborated a bit are here: 

https://concourse-ci.org/on-failure-step-hook.html
https://concourse-ci.org/on-error-step-hook.html
https://concourse-ci.org/on-abort-step-hook.htm

It is somewhat unclear to me what the difference is between these 3. It would be nice to precisely explain under what circumstances a step is considered as 'aborted' versus 'failed' versus 'errored'. It seems to be that all 3 are somehow similar in that they all trigger when a step stopped in a 'abnormal' way. The difference between the 3 however is really just a bit of guessing. 

If I were to guess then I'd say that 'error' and 'failure' are synonyms. But 'abort' happens when the user stops the job/task from the ui.

Is this guess correct? I really have no idea, which is exactly why I think the docs could do with some further explanation.

**Comment by pivotal-jamie-klassen** [comment]
I just looked at
https://github.com/concourse/concourse/blob/master/atc/config.go/#L320-L330 and I see slightly better prose descriptions in the comments.

**Comment by marco-m** [comment]
hello @kdvolder :-)

the names have a 1-to-1 mapping with the Concourse UI that appears (and then disappears after a few seconds) if you move the mouse inside a pipeline view. See for example the public https://ci.concourse-ci.org/teams/examples/pipelines/job. I am reporting below a screenshot.

My way to remember the difference is by the color.

- failed -- on_failure -- red color: if the user script/task returned a non-zero exit code. Classic example failed compilation or failed test. Can also happen on a resource, for example if the resource returns a syntax error in how it has been configured or returns an external API error. This is definitive on a given build.
- errored -- on_error -- orange: if something went wrong at Concourse level. For example: if there are no more workers (temporary) to run a task or resource.
- aborted -- on_abort -- brown: if, as you mention, the user aborted the job.

<img width="182" alt="legend" src="https://user-images.githubusercontent.com/3075069/67597611-e52cf180-f76b-11e9-8ad1-5f9b4f5eca0a.png">

**Comment by pivotal-jamie-klassen** [comment]
OK, so I tried to write up a comprehensive list of scenarios corroborating @marco-m's observations, but I realized it's a pretty big list. What I came up with so far:
* `on_abort` runs the hook whenever the hooked step's `Run` method returns a `context.Canceled` error: https://github.com/concourse/concourse/blob/master/atc/exec/on_abort.go#L34-L37. Analyzing the various codepaths that might cause this to happen (I had hoped to write out the full analysis but it's a bit too long), I'm fairly sure it's only if the [AbortBuild](https://github.com/concourse/concourse/blob/master/atc/api/buildserver/abort.go) API action occurs, which is when you click the X in the web UI or run `fly abort-build`.
* `on_error` runs the hook whenever the hooked step's `Run` method returns any other error: https://github.com/concourse/concourse/blob/master/atc/exec/on_error.go#L39-L46
    * for a task, an error can happen:
        * if related resource versions (honestly I don't know how tasks make use of resource versions) fail to be interpolated using data from a credential manager: https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L126-L129
        * if the task config cannot be fetched - like if you have `file:` configured but the file doesn't exist, or if you specified `config:` with bad YAML, or used `((variables))` in either of these cases that couldn't be interpolated: https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L159-L167
        * if you specified `image:` in the config, but the thing you referenced (typically a resource or output of a prior task) can't be found: https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L279, via https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L178-L181
        * if any of the task's non-`optional` `inputs` cannot be located (those should be coming from prior `get` steps or `outputs` from prior tasks, potentially referenced via an `input_mapping`): https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L325-L327, via https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L183-L186
        * if the task runs longer than its specified `timeout`, or if the runtime encounters any other problems (like if the task has specified `tags:` and there are no matching workers, or if any calls to garden or baggageclaim timeout or error): https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L234-L243
    * for a get from or a put to a resource, this would happen in cases like the script outputting invalid JSON, any `((variables))` in the `params:` failing to be interpolated, or any runtime-related problems.
* `on_failure` runs the hook whenever the hooked step's `Succeeded` method returns `false` after `Run` has completed: https://github.com/concourse/concourse/blob/master/atc/exec/on_failure.go#L34-L36
    * for a task, `succeeded` is `true` if and only if the task process exited with a status of 0: https://github.com/concourse/concourse/blob/master/atc/exec/task_step.go#L245
    * if the script (like `/opt/resource/in` or `/opt/resource/out` underlying get from or put to a resource executes to completion but returns a nonzero status code: https://github.com/concourse/concourse/blob/master/atc/resource/run_script.go#L118-L126

**Comment by marco-m** [comment]
@pivotal-jamie-klassen I was wondering if there is a way to give a sort of high-level rule of thumb when looking at a failure (red) as opposed to an error (orange).

For example, a failure (red) has two characteristics and in general is easier to understand: it is always caused directly by user code and it is permanent for a given build. Inside a red there are two subcategories:
1. Caused by the pipeline configuration. For example, a misconfigured resource will cause a failure.
2. The "normal", easy to understand failure: user code failed a build or a test.

An error (orange) on the other hand is more difficult to classify. Some oranges are temporary and unrelated to a given build, for example a temporary failure of a resource check. Some other I _think_ are permanent (need user intervention to be fixed), although I cannot think of an example right now.

**Comment by kdvolder** [comment]
I like @marco-m high-level classification. I cannot vouch of course for its correctness... But it is this kind of classification that I'd like to see. If I understand correctly then:

- on_abort: the user stopped the task via ui or cli.
- on_failure: the user's script code was executed, but it failed.
- on_error: anything else that when wrong (i.e. more like a problem inside concourse itself, or maybe a bug in a resource implementation).

Maybe `on_error` is harder to classify by listing every case... because its more of a 'everything else' category?
