### ISSUE TITLE
Is 'on_error' supported as a Job attribute?

### ISSUE THREAD

**Issue by kdvolder** [concourse/docs#268]
What I mean is, there are step hooks like `on_failure`, `on_abort`, `on_success` and `on_error`.

Step hooks `on_failure`, `on_abort`, `on_success` are listed in the docs as being also acceptable as attributes on a Job directly (bottom of this page: https://concourse-ci.org/jobs.html).

The `on_error` step hook is not mentioned there. Is this an oversight in the docs?

Related issue: https://github.com/spring-projects/sts4/issues/383

**Comment by pivotal-jamie-klassen** [comment]
job configs can definitely have an `on_error`: https://github.com/concourse/concourse/blob/master/atc/job_config.go#L18, so this is a gap in the docs! Would you consider making a PR to https://github.com/concourse/docs/blob/master/lit/docs/jobs.lit?

**Comment by pivotal-jamie-klassen** [comment]
fixed in #269
