### ISSUE TITLE
Content strategy rework

### ISSUE THREAD

**Issue by vito** [concourse/docs#28]
Note: this issue is being made a little late. All work here is done on the `humble` branch, and this issue is tracking what's left to do.

# Needed for MVP

## General
- [ ] Skim around and watch for anything that seems "jarring" - look for things that were moved around quickly without being finessed into its new context (if needed).
- [x] Look for code blocks whose content overflows into the margin (too long)
- [x] Need a reference to Security and mailing list
- [x] Link to the blog!
- [x] Still need a "get started in 5 minutes" flow.

## Front Page
- [x] Show current pipeline UI, not beta
- [x] Better blurb; "It's ..." feels weak for being in such a prominent place. What else can we say here? Maybe nothing? Maybe a link to the About page?

## "About"
- [x] "How can I help?" section may feel a bit out of place.

## "Downloads"
- [x] Needs design for the release notes (i.e. fix/feature/breaking)
- [x] Replace with single "Download" page optimizing for quick access to binaries for latest release (link to separate page for older releases?)

## "Install"

Majorly rethink focus here and maybe subsume into single "Download/Install" page. Focus on binary, link to GitHub repos for more targeted methods (i.e. `concourse-deployment` for BOSH, `concourse-docker` for Docker), something for Kubernetes.

- [x] Get rid of BOSH section; just link to `concourse-deployment` repo somewhere prominent.
  - We don't want to teach people BOSH. may be better to just focus on people that are already familiar with it and can just take the deployment repo and run with it. current approach scares some people as they assume they have to learn BOSH.
- [x] Get rid of the Docker section; delegate to `concourse-docker` repo.
- [x] Get rid of "Single VM" section; use Docker as the single-command getting-started (NOTE: this depends on https://github.com/concourse/concourse/issues/2069).
- [x] To replace "single VM" quick start, implement https://github.com/concourse/bin/issues/40
- [x] Tag versions of concourse-deployment and have releases link to the appropriate tag

# Not needed for MVP

## "Builds"
- [ ] Any other useful stuff to put here?
- [ ] Fix broken `aside`s

## "Pipelines"
- [ ] Describe what pipeline-y things happen to configured resources and jobs.

## "Jobs"
- [ ] Describe their scheduling in more detail.

## "Resources"
- [ ] Describe their lifecycle, when they're checked, etc.

## "Administration"
- [ ] intro? This is currently just a list of `fly` commands.

## "Metrics"
- [ ] Refresh; it's very out of date and still refers to Riemann

## "Worker Pools"
- [x] Remove; don't think it's very useful and it's very BOSH oriented.

## "Web UI"
- [ ] pipeline web-ui breakdown
- [ ] dashboard

## "Contributing"
- [x] ways to contribute
- [ ] getting started with docs
- [x] getting started with code contribution
- [ ] Concourse CLA

## "Community Mentions"
- [ ] some way to showcase who's using Concourse

**Comment by vito** [comment]
Also just linking https://github.com/concourse/concourse/issues/2003 to this in the meantime, so we don't forget.

**Comment by jama-pivotal** [comment]
I'd be willing to volunteer myself to do a section on Pipeline Visuals and the Dashboard (TM), but that'd be for not MVP

**Comment by jama-pivotal** [comment]
oh man, this new site should have search @vito pls

**Comment by wshayes** [comment]
I was going to consolidate the Job/Pipeline Badge information into a doc section, but then I saw the documentation engine and bailed. Could you use something like Sphinx/ReadTheDocs which is pretty common or MkDocs (markdown-based)? built-in search, pretty well known, the simpler the documentation system the more docs get built.  I typically use the edit links to fix typo's, mistakes as PR's if it's quick and easy.

Not saying I'm not impressed with the ability to create your own GO static documentation engine @vito, but my head is already bursting with systems/tools/applications.

**Comment by vito** [comment]
@wshayes Sorry, but I think at this point the trade-off is worth it. We've used various docs engines over the years, and started with conventional tooling and it was just too frustrating not having enough control and flexibility in how we wanted to structure everything, and having links silently break as we moved content around.

We used [Scribble](https://docs.racket-lang.org/scribble/) for a while which was great but the toolchain was pretty inaccessible to contributors. So Booklit is our middle ground.

Booklit is fully documented [here](https://vito.github.io/booklit), and honestly shouldn't take that much to "fake it til you make it", especially if it's just typo fixes. It helps us a *lot*, and should only take running `./scripts/build` to get a feedback loop.

**Comment by marco-m** [comment]
@vito would it make sense to have a mini section for the docs, called "how to contribute", that points to https://vito.github.io/booklit ?

**Comment by vito** [comment]
@marco-m Yeah, totally. Maybe like how some sites have a "help fix/improve the docs" link?

**Comment by marco-m** [comment]
@vito yes, that would be even better (the banner)

**Comment by jama-pivotal** [comment]
Labelled this with docs and community and gonna let it marinate for a bit. For future readers, please submit new issues in our docs repo https://github.com/concourse/docs/issues
