### ISSUE TITLE
Update sidebar pipeline snippet to use registry-image, not docker-image

### ISSUE THREAD

**Issue by deniseyu** [concourse/docs#284]
On this page we have a pipeline snippet in the right hand column: https://concourse-ci.org/resource-types.html

The example uses `docker-image`, which is an older method of interacting with the Docker API; the newer, more recommended way is to use the `registry-image` which contains retries and other resiliency features.

We should update this snippet to nudge Concourse users towards the recommended way of doing this!

**Comment by vito** [comment]
This is done now 👍
