### ISSUE TITLE
Encryption clarification

### ISSUE THREAD

**Issue by craigjbass** [concourse/docs#304]
How true is https://github.com/concourse/docs/blob/master/lit/docs/auth.lit#L55 with current versions of concourse?

Specifically what connections are not encrypted? Can anyone point me to specific lines of code where these connections are made

Is there any protocols in use other than HTTPS, if an SSL certificate is setup?

**Comment by vito** [comment]
answered in https://github.com/concourse/concourse/discussions/5419
