### ISSUE TITLE
Adding how to install fly cli

### ISSUE THREAD

**Issue by ChrisJBurns** [concourse/docs#311]
I've just followed the guide and used the Concourse CI to download the mac binary for the `fly` CLI. However it doesn't say to insert into `/usr/local/bin` directory. Perhaps it should, I know from experience to put it there, but someone new may not know this.

Just a suggestion.

**Comment by taylorsilva** [comment]
Recent docs changes cover this I think. The install should be much easier to follow for users not familiar with the terminal
<img width="771" alt="image" src="https://user-images.githubusercontent.com/4583837/125518523-7dee8cce-0472-478f-b6a3-aae48f3be355.png">
