### ISSUE TITLE
Metrics sample dashboard link no longer resolves

### ISSUE THREAD

**Issue by jpanderson-outreach** [concourse/docs#340]
The link to your sample dashboard no longer follows as it appears `metrics.concourse-ci.org` isn't running. Is there another sample Datadog dashboard we can work from to understand what are good metrics to watch and how best to visualize them? I know that for us this is something we've struggled with in getting a handle on operating Concourse. 

https://metrics.concourse-ci.org/dashboard/db/concourse

**Comment by chenbh** [comment]
Hi @jpanderson-outreach, you can find our Datadog dashboad [here](https://p.datadoghq.com/sb/bb663c3fb-c0f3ba68561631a1b130a4507bf36a15) which is configured by https://github.com/concourse/greenpeace/tree/master/terraform/dashboard.

We also have a SLI suite at https://github.com/concourse/oxygen-mask which emulates common user actions like viewing build history and triggering builds before reporting it to Datadog.

**Comment by jpanderson-outreach** [comment]
@chenbh thanks! I opened https://github.com/concourse/docs/pull/345 to update the docs to link there.

**Comment by jpanderson-outreach** [comment]
Also, it looks like the `greenpeace` repository is a private repository, or at least not visible to me. But the Dashboard alone gives us something good to build from.
