### ISSUE TITLE
document set_pipeline step automatic archiving

### ISSUE THREAD

**Issue by chenbh** [concourse/docs#346]
https://github.com/concourse/concourse/issues/4873

**Comment by scottietremendous** [comment]
@chenbh - Can I close this?

**Comment by chenbh** [comment]
https://github.com/concourse/concourse/pull/5854 is still open and I don't think it's documented yet:
https://github.com/concourse/docs/blob/7943ea1e8a5e663694870eae72e639b35bbbadd5/lit/docs/jobs/steps.lit#L567-L599
