### ISSUE TITLE
Suggestion: Directory of companies offering Concourse services

### ISSUE THREAD

**Issue by DanielJonesEB** [concourse/docs#367]
I'd like to propose a new section on the Concourse website. I'm not quite sure if this is the best place or manner in which to raise the suggestion though!

### Proposal

I propose the addition of a **directory/marketplace of organisations offering Concourse-related services** to the main [concourse-ci.org](https://concourse-ci.org/) website. This would be similar to the [CNCF's KCSP Partners list](https://kubernetes.io/partners/#kcsp) (albeit with no certification in place) and the [Cloud Foundry Foundations 'Foundry' directory](https://www.cloudfoundry.org/thefoundry/).

It would appear in the top-level navigation and would feature an alphabetically-ordered list of organisations offering Concourse services, such as hosted Concourse, training, consultancy, and others. If the directory became too large and unwieldy then at some future point it could be subdivided by service.

New additions should find their way into the directory via pull request in order ensure tolerable levels of marketing-speak. A short submission guidelines document (maybe a couple of paragraphs) would highlight acceptable forms of submission. Suggested rules would include limit on unsubstantiated claims, word count, a single link, a single logo, and that the submitter of the PR is raised by a member of the GitHub organisation being promoted (ie someone from EngineerBetter couldn't raise a PR for a submission on behalf of our friends at Stark & Wayne).

For example, acceptable:

> [FooCo](url) deliver instructor-led Concourse training and consultancy, including Concourse 'healthchecks' that cover both system performance and usage of Concourse. Additonally FooCo maintains the open-source Concourse deployment tool Tower-Of-Control.

Unacceptable:

> FooCo are the most-loved [Concourse consultancy](url), with [industry leading techniques](url) that can solve your [every Concourse need](url)... _continue ad nauseam_

### Benefits

* Concourse users will find it **easier to seek professional support**, which in turn may lessen the burden on voluntary support mechanisms (forum, Discord)
* Potential enterprise Concourse users will have **increased confidence in adopting Concourse**, knowing that they can receive help if required. Often having a support plan is mandated by various regulatory frameworks, and whilst an acceptable plan may include having a proficient internal team, many organisations choose to cite support agreements with professional services companies instead.
* Concourse-supporting organisations will be helped by customers being able to more-easily find them. **If those with a vested financial interest in Concourse are successful, it is reasonable to assume that this will feed into an increased level of code contributions** and evangelism.

### Risks/Costs

* Initial effort in designing and adding new section to website
* **Maintenance and upkeep** of submission PRs
* **Drama** relating to the acceptance of submissions - for instance, what happens if a submission is rejected because approvers consider an offering 'sketchy'?
* **'Dirtying' of Concourse brand** by having main website linking to commercial offerings

**Comment by taylorsilva** [comment]
You did it! #420

**Comment by DanielJonesEB** [comment]
Ha, and I didn't even follow my own suggestion. Never trust a person with a moustache.
