### ISSUE TITLE
Confusion if we are looking at the tutorial or documentation.

### ISSUE THREAD

**Issue by norman-abramovitz** [concourse/docs#37]
<img width="1095" alt="screen shot 2018-04-03 at 10 42 42 am" src="https://user-images.githubusercontent.com/13754664/38265894-041fa378-372c-11e8-9ef1-206be5693f02.png">

I was looking at how to reach the tutorial from the concourse site.   Looking at the image snapshot above I thought I was in the tutorial, but I was looking at the documentation.

I will leave how you want to change the UI to the people who know more.   Also, it could make sense to add a sentence or two as well on the homepage about the where to find the tutorial even if you fix the links.

**Comment by sampeinado** [comment]
I removed the orange highlight. Closing the issue now.
