### ISSUE TITLE
Fly intercept rendering overlap

### ISSUE THREAD

**Issue by o-orand** [concourse/docs#38]
Hi !
As you can see on the image below, [fly intercept documentation](https://concourse-ci.org/builds.html#fly-intercept) rendering overlaps. I've tried on firefox (v55) and on chronium (v64).
![image](https://user-images.githubusercontent.com/976115/38302461-13e6f40a-3803-11e8-8825-014ec4416fec.png)

**Comment by jama-pivotal** [comment]
Looks like the CSS to make the annotation appear in the gutter is with a `right: 200px` which literally force places the annotation to the right, so its not smart enough to flow the annotation blocks nicely (and detect overlaps). I've hackily fixed this by forcing the annotation lower in the content flow of the `build.lit` file, which eliminates the overlap. If we keep writing annotations through we should probably use a "proper" three column layout
