### ISSUE TITLE
[cadet] Is your codebase open-source?

### ISSUE THREAD

**Issue by c4lliope** [concourse/docs#383]
Hello, concourse.

I am very intrigued by your project management software at https://project.concourse-ci.org/;
from the page's GitHub authentication it looks like the program is called "Cadet".

I haven't seen anyone else using such a program, so I assume it is under development by the Concourse team?
Is this a codebase that you are planning to open-source, or am I misreading the situation and it is someone else's responsibility?

Much obliged.

**Comment by c4lliope** [comment]
on second consideration, you're more likely using an third party library, and have simply imposed the aeronautical name "cadet" in a configuration. If such is the case, I'd be very happy for a referral to the program.

Cheers!

**Comment by taylorsilva** [comment]
Cadet is made by @vito and the code is her: https://github.com/vito/cadet

**Comment by vito** [comment]
Haha, yeah it ain't the prettiest codebase either. It's very much a "the team needs this feature so I'll hack it together in a weekend" project. Happy to answer questions or help get it up and running though.
