### ISSUE TITLE
Create a Community Guides section

### ISSUE THREAD

**Issue by jama-pivotal** [concourse/docs#41]
I think we have enough links that we consistently link out that we should collect them into a single place. For example, I've already done this in the Pivotal Concourse for PCF documentation: https://docs.pivotal.io/p-concourse/guides.html

In addition to the guides listed there, we can add:

* Concourse Badges http://engineering.pivotal.io/post/concourse-badges/ and related issue https://github.com/concourse/concourse/issues/2086
* https://www.digitalocean.com/community/tutorials/how-to-install-concourse-ci-on-ubuntu-16-04
* https://www.digitalocean.com/community/tutorial_series/setting-up-and-using-concourse-ci-on-ubuntu-16-04
* https://www.digitalocean.com/community/tutorials/how-to-set-up-continuous-integration-pipelines-with-concourse-ci-on-ubuntu-16-04
* https://www.digitalocean.com/community/tutorials/ci-cd-tools-comparison-jenkins-gitlab-ci-buildbot-drone-and-concourse
* https://www.digitalocean.com/community/tutorials/how-to-secure-concourse-ci-with-ssl-using-nginx-on-ubuntu-16-04

**Comment by jama-pivotal** [comment]
Just found this article on writing Concourse Custom Resources as well that I should probably include https://itnext.io/writing-a-custom-resource-for-concourse-detecting-pull-request-close-merge-events-e40468eb2a81

**Comment by BrianMMcClain** [comment]
Tossing this one onto the pile: https://content.pivotal.io/blog/developing-a-custom-concourse-resource
