### ISSUE TITLE
Inline examples no longer render

### ISSUE THREAD

**Issue by ewiner** [concourse/docs#429]
Using the latest Chrome, https://concourse-ci.org/hello-world-example.html and other doc pages no longer can show the inline `ci.concourse-ci.org` iframes, because of the `frame-ancestors 'none'` CSP rule set by https://github.com/concourse/concourse/pull/6949.

![image](https://user-images.githubusercontent.com/603747/119054365-80606a00-b995-11eb-85f4-a7f0c9d2ce87.png)

**Comment by taylorsilva** [comment]
Ah it's the CSP headers we added!
https://github.com/concourse/concourse/pull/6949
We'll have to change this to make them work again.

Firefox at least gives a better error message. Chrome's is a misleading:
<img width="777" alt="image" src="https://user-images.githubusercontent.com/4583837/119151572-86019280-ba1d-11eb-90d7-b0a654d26323.png">

**Comment by aoldershaw** [comment]
Ah man, I knew this would happen but totally forgot to update! https://github.com/concourse/concourse/pull/6949#pullrequestreview-651341826

Thanks for the report, should be fixed now.

@taylorsilva can you close the issue? I'm not able to as I'm not on the community team atm
