### ISSUE TITLE
Download Page

### ISSUE THREAD

**Issue by pn-santos** [concourse/docs#47]
The current download page requires me to scroll down in order to see the latest version and associated release notes (on a 1080p screen), I feel the current logos and sections for the download links (Linux/Mac OS X etc) are way too big and take up a lot of space.

I have no idea if it's possible but maybe the logos could be reduced a little bit in size and maybe have the layout with two columns for the download links? 
Another option (again no idea if possible) would be to have two tabs in the download section, one with download links and another one with release notes.

**Comment by jama22** [comment]
Check out the new design!
