### ISSUE TITLE
Broken link on the Job & task hooks example page

### ISSUE THREAD

**Issue by quatran** [concourse/docs#496]
The link [Step hooks](https://concourse-ci.org/on-success-step-hook) on the page [Job & task hooks example](https://concourse-ci.org/hooks-example.html) seems to be broken.

**Comment by xtremerui** [comment]
Fixed in https://github.com/concourse/docs/commit/2bd85ca7ac9e3aaed399c0b469b71f262cd9e23c. Thank you!
