### ISSUE TITLE
Concourse site should handle 404s in a nicer way

### ISSUE THREAD

**Issue by jama22** [concourse/docs#50]
The current site is powered by booklit; its useful in converting booklit markdown into html pages. However, since all it does is generate html files, it doesn't have some of the nice functions like 404 redirects!

In the instance of a 404, we should send the user to a 404 page letting them know the page no longer exists, instead of a nasty nginx error

**Comment by osis** [comment]
Now that it's on Github pages, you get the default Github one. We should probably still do something cooler though. https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by taylorsilva** [comment]
The github 404 page gonna have to be good enough.
