### ISSUE TITLE
Sidebar Subsection Heirarchy

### ISSUE THREAD

**Issue by sampeinado** [concourse/docs#58]
Currently the left sidebar displays one primary menu persistently, but can also display submenus. These submenus have the same style as the primary menu, so their style does not make it clear that they are hierarchically different than the primary menu. See my comment below for a walkthrough of how the sidebar renders in different situations. 

 # Recommendations
I understand that I don't fully understand the reasoning behind Booklit's rendering of parent and children menus, so I am going to make two separate recommendations, one that would be a larger change (and I am not sure is possible) and a second one that is a smaller change (but I am confident is possible and would still be an improvement). 

 ## Option 1 (preferred)
![screen shot 2018-05-02 at 12 18 48 pm](https://user-images.githubusercontent.com/35495560/39535875-0908e9b0-4e03-11e8-83bb-d54e4de5c209.png)
- [ ] Remove the blue highlight that shows the current page. The underline and darker text color is enough of a marker to show the current page. 
- [ ] Nest child nodes within parent nodes to avoid repetition of titles and to show hierarchy. Nesting and indenting children may seem like a bad solution given that sidebar width is a limited resource, but the current use of numbering is effectively functioning as an indent since it increases by two additional characters with each successive child (see figure A below). 
- [ ] Decrease the opacity to 50% of the text for all parent nodes (in order to bring the current menu into highlight).
- [ ] Change the color of the line that comes down from the triangle point when a menu is open (color: #D6D6D6).
- [ ] Remove the numbering from, preferably all, but at least the 3rd and 4th level child nodes (no need for "5.6.2.1").

 ## Option 2
![screen shot 2018-05-02 at 12 18 52 pm](https://user-images.githubusercontent.com/35495560/39535885-0d7ee508-4e03-11e8-8e8c-f1600a49531b.png)
- [ ] Remove the numbering from (at least) the 3rd and 4th level child nodes (no need for "5.6.2.1").
- [ ] If you decide to keep the numbers, then change their color to be lighter than the titles themselves (font-color: #D6D6D6). 
- [ ] Remove the blue highlight that shows the current page. The underline and darker text color is enough of a marker to show the current page. 
- [ ] Remove the line that comes down from the triangle point when a menu is open.
- [ ] Decrease the opacity to 50% of the text for all parent nodes (in order to bring the current menu into highlight).

 ### Figure A
Showing that the numbering system is effectively an indent for child menus:
![screen shot 2018-05-02 at 12 18 56 pm](https://user-images.githubusercontent.com/35495560/39535893-1468a55c-4e03-11e8-81d5-998d3095de64.png)

**Comment by Lindsayauchin** [comment]
@sampeinado can we see what those ideas would like using the current UI?

**Comment by sampeinado** [comment]
Here is an example of how the sidebar renders as the number of children increases:

### 1. The menu starts out displaying like this, with the current page being highlighted in blue:

![screen shot 2018-05-01 at 5 11 10 pm](https://user-images.githubusercontent.com/35495560/39528900-5edc6d22-4df3-11e8-8c95-1fadbb41ef12.png)

 ### 2. When you click one of the menu options, the new current page is highlighted in blue in both the parent menu and the child menu:

![screen shot 2018-05-01 at 5 11 14 pm](https://user-images.githubusercontent.com/35495560/39528938-7501e10e-4df3-11e8-88e7-68da834be777.png)

 ### 3. When you click one of the menu options of the child node, the child of the child displays in the body of the page:

![screen shot 2018-05-01 at 5 11 25 pm](https://user-images.githubusercontent.com/35495560/39529644-297a927e-4df5-11e8-9df4-130a86ceb49c.png)

 ### 4. When you click into one of those links, you are brought to the relevant section of the body:

![screen shot 2018-05-01 at 5 11 45 pm](https://user-images.githubusercontent.com/35495560/39529795-850afaa2-4df5-11e8-8fc5-c741edd2f789.png)

 ### 5. On that same page, the sidebar menu shows the following menus:

![screen shot 2018-05-01 at 5 12 02 pm](https://user-images.githubusercontent.com/35495560/39530076-2777c3c4-4df6-11e8-99d0-0eea7ca9b2fe.png)
