### ISSUE TITLE
"Docs" section is unreachable

### ISSUE THREAD

**Issue by walterdolce** [concourse/docs#65]
Hi. This link leads to a 404: https://concourse-ci.org/docs.html

Not sure where that link should lead. Let me know where it should lead please and I will send a pull request straight away. ;)

**Comment by jama-pivotal** [comment]
I think this was due to us renaming "docs" to "reference" (https://concourse-ci.org/reference.html) . I found a reference to that in our README for this repo, can you point me to other broken links?

**Comment by danielwhatmuff** [comment]
I've come across a lot of 404s when accessing links back to concourse docs. Might want to check the nginx logs for the last few weeks!

**Comment by jama-pivotal** [comment]
Closing for now
