### ISSUE TITLE
The 'new look' (not sure since when?) looks awful on wider screen

### ISSUE THREAD

**Issue by kdvolder** [concourse/docs#70]
Everything is smashed together in the left-side of the screen. This is kind of ugly and impractical. The navigation menu on the left, for example could easily use some extra space (so it doesn't have to wrap as much and is easier to read and less ugly). And also the content on the right feels like it is bit narrower than is pleasant to read. So when you have the extra space, why not use it?

See image, it speaks for itself:

![smashed-on-left-concourse-site](https://user-images.githubusercontent.com/1002156/40520760-b4daacd0-5f7c-11e8-8db9-f961869c2cf1.png)

**Comment by vito** [comment]
Personally I don't like it when documentation fills up my whole screen. I like being able to use a huge monitor for more than one thing at a time, which is especially useful when you're working on something in a terminal and also referencing the docs at the same time.

Reading paragraphs stretched across a page also hinders readability. It means your eyes have to travel farther from the end of one line to the beginning to the next, and you could end up on the wrong line. It can also end up feeling a bit like this:

![wide](https://user-images.githubusercontent.com/1880/45513654-4284ff80-b771-11e8-9af7-4381722eb237.gif)

Also, we *do* use that whitespace when there's actually something to put there. For example, most of our reference pages put examples alongside the content:

* https://concourse-ci.org/tasks.html
* https://concourse-ci.org/pipelines.html

Sure, on some pages it can look like a lot of wasted space. We could maybe fill it in with the grey background that we use for pages that have example content for the margins. That would at least make the text feel cushioned by something.

We could also make the main column a tad wider, we'd just have to be careful not to make it so wide that we can't have example content in the margins anymore (it'd be a shame to wrap it on common laptop resolutions). To me it doesn't really seem worth it, to be honest.

In any case, please try to not sound so dramatic and abrasive when giving feedback. Consider the humans on the other side of the screen. Calling someone's website awful (especially for such a minor concern) is not very nice. This is not the first time we've had to warn you about how to communicate feedback effectively.
