### ISSUE TITLE
Unknown command quickstart

### ISSUE THREAD

**Issue by mcnichol** [concourse/docs#73]
When running:
`$> wget https://concourse-ci.org/docker-compose.yml`
`$> docker-compose up`

Receiving the errror:

```concourse_1     | Unknown command `quickstart'. Please specify one command of: land-worker, retire-worker, web or worker```

It appears that: `command: quickstart` is not a valid command for the docker-compose file.

**Comment by osis** [comment]
Hey @mcnichol, I just tried this on a net-new machine and it seems okay.

Can you give some more information on your setup?

**Comment by brandocorp** [comment]
I was having the same issue. I cleaned out all of my local images and did another `docker-compose up` and it seems to be working now.

I would try `docker rmi concourse/concourse` if you're running into this issue.

**Comment by mcnichol** [comment]
@brandocorp - That was in fact the issue....scorched the earth and worked fine.
