### ISSUE TITLE
No documentation for Kubernetes credential manager

### ISSUE THREAD

**Issue by rubenv** [concourse/docs#96]
Just found out that there's a Kubernetes creds plugin, which is completely undocumented. Might help to add a bit about this.

**Comment by michaelmeelis** [comment]
I'm using this as well and it really confuses me in certain times. I would love some examples with the docker repositories or some more details how it is fetched.

**Comment by cirocosta** [comment]
Hi @rubenv and @michaelmeelis ,

That is indeed something that is missing, thanks for raising that!

For the moment, you can refer to https://github.com/helm/charts/blob/master/stable/concourse/README.md#kubernetes-secrets for an example of how to make use of secrets as the credential manager for your pipelines.

We're currently improving how users experience Concourse on top of k8s (e.g., integration tests running on top of k8s regarding this feature was being added just yesterday), so we should have that added to the docs soon with some examples.

Meanwhile, **do you have any specific details that you'd like to know there**?

Thanks!!

**Comment by rubenv** [comment]
Was able to figure it out from that one. It was just slightly annoying to roll out Vault on our test cluster only to then find out that there's a simpler solution based on Kubernetes.

A simple note in the Concourse docs that a Kubernetes-secrets-based option is available would've saved a ton of time.

**Comment by cirocosta** [comment]
Hey,

@mhuangpivotal and I are taking this one today, here's what we're thinking about:

- [ ] How it works
  - [ ] How secrets lookups are performed
- [ ] Coonfiguration
  - [ ] Permissions that you need
  - [ ] Access
    - [ ] From within the cluster
    - [ ] From outside the cluster
- [ ] Interpolation gotchas
- [ ] Examples
  - [ ] kubernetes objects needed

Thanks!
