### ISSUE TITLE
Quick Start / Tutorial on homepage broken

### ISSUE THREAD

**Issue by stefanbethke** [concourse/docs#97]
Right now, the quick start box on the home page offers a docker-compose setup, and then invites the reader to follow the examples in the https://concoursetutorial.com tutorial.

Following the instructions, the tutorials do not work due to authentication issues with the web site. (Fly appears to work fine.)

The problem appears to be that the docker-compose.yml off the home page pulls the latest docker image, which appears to have authentication issues, whereas the tutorial is pinned to 3.4.1 and working.

To avoid confusion, the box should probably be renamed Tutorial or "Tutorial Quick Start" or similar, and use the docker-compose.yml from the tutorial Git repo. Essentially, the instructions from 
https://concoursetutorial.com/#getting-started should be copied or referenced.

It might also be worthwhile pointing out the Quick Start section from https://concourse-ci.org/install.html#quickstart. This quick start however is much more complicated that then tutorial setup, and I'd recommend concentrating on having the working tutorial be featured prominently on the home page. The quality of the tutorial is a major asset to the project, from my very fresh experience.

**Comment by holmboe** [comment]
Adding a, hopefully helpful, link to the backstory of this issue: https://discuss.concourse-ci.org/t/homepage-quickstart-docker-compose-setup-broken/447

**Comment by cirocosta** [comment]
Hey @stefanbethke and @holmboe ,

What is the specific error that you're facing on the web UI? Is it a 400 Bad Req after typing your user and password (`user=test pw=test`)? That might happen if you've landed on the UI via something like `localhost` while the `external-url` set for `atc` is `127.0.0.1` (there's a cookie that gets set for the external URL) - that's my 2cents.

Please let me know if that helps!

Thx

**Comment by marco-m** [comment]
Is this issue still valid ?

**Comment by marco-m** [comment]
The PR above will unbreak the quickstart and enable a decent UX for a first comer. I think that the details in this issue are old, but in any case it is still true that the current (2019-06) quickstart is broken.
